services:
  report-service:
    build: ./report-service
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    env_file:
      - ./report-service/.env

  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - report-service

  event-service:
    build:
      context: ./event-service
    ports:
      - "8081:8081"
    restart: always
